language: c
sudo: false
os:
  - linux
  - osx

env:
  - LUA='Lua5.1'
  - LUA='Lua5.2'
  - LUA='Lua5.3'
  - LUA='LuaJIT2.0'
  - LUA='LuaJIT2.1'

before_install:
  - bash ci/setup.sh

install:
  - bash ci/install.sh

script: bash ci/test.sh
